package co.edu.cue.subastasYa.entity;

public enum Ciudad {
    BOGOTA, MEDELLIN, CALI, BARRANQUILLA, CARTAGENA, SOLEDAD, CUCUTA, IBAGUE, SOACHA, VILLAVICENCIO,
    BUCARAMANGA, SANTA_MARTA, VALLEDUPAR, BELLO, PEREIRA, MONTERIA, PASTO, BUENAVENTURA, MANIZALES, NEIVA,
    PALMIRA, RIOHACHA, SINCELEJO, POPAYAN, ITAGÜI, FLORIDABLANCA, ENVIGADO, TULUA, SAN_ANDRES_DE_TUMACO, DOSQUEBRADAS,
    APARTADO, TUNJA, GIRON, URIBIA, BARRANCABERMEJA, FLORENCIA, TURBO, MAICAO, PIEDECUESTA, YOPAL
}
